CREATE TABLE store_online.Customers (
    customer_id INT PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(100),
    phone VARCHAR(20),
    address VARCHAR(100)
);

CREATE TABLE store_online.Products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100),
    category VARCHAR(50),
    price DECIMAL(10, 2)
);

CREATE TABLE store_online.Orders (
    order_id INT PRIMARY KEY,
    customer_id INT,
    order_date DATE,
    total_amount DECIMAL(10, 2),
    FOREIGN KEY (customer_id) REFERENCES store_online.Customers(customer_id)
);

CREATE TABLE store_online.OrderItems (
    order_item_id INT PRIMARY KEY,
    order_id INT,
    product_id INT,
    quantity INT,
    FOREIGN KEY (order_id) REFERENCES store_online.Orders(order_id),
    FOREIGN KEY (product_id) REFERENCES store_online.Products(product_id)
);

INSERT INTO Customers (customer_id, first_name, last_name, email, phone, address)
VALUES
(1, 'John', 'Doe', 'john.doe@example.com', '123-456-7890', '123 Main St, City'),
(2, 'Jane', 'Smith', 'jane.smith@example.com', '987-654-3210', '456 Elm St, City'),
(3, 'David', 'Johnson', 'david.johnson@example.com', '555-555-5555', '789 Oak St, City');  
INSERT INTO Products (product_id, product_name, category, price)
VALUES
(1, 'Laptop', 'Electronics', 1000),
(2, 'Smartphone', 'Electronics', 800),
(3, 'T-shirt', 'Clothing', 20),
(4, 'Shoes', 'Clothing', 50),
(5, 'Headphones', 'Electronics', 150);
INSERT INTO OrderItems (order_item_id, order_id, product_id, quantity)
VALUES
(1, 1, 1, 1),
(2, 1, 2, 2),
(3, 2, 3, 3),
(4, 3, 4, 1),
(5, 4, 1, 1),
(6, 4, 5, 1),
(7, 5, 2, 1),
(8, 5, 3, 2);
#How many customers are there in the database?
select count(*) from Customers;
SELECT COUNT(*) AS customer_count FROM Customers;

#What is the total number of orders placed?
select count(*) as order_placed_count from Orders;
#What is the total revenue generated by the store?
select sum(total_amount) as revenue from Orders;
#Which customer has placed the most number of orders?
SELECT customer_id, COUNT(*) AS order_count FROM Orders GROUP BY customer_id
ORDER BY order_count DESC Limit 1 ;
# What is the average order value?
select avg(total_amount) as average_order_value from Orders;
#Which products have the highest prices?
select product_name ,price from Products order by price desc limit 1;
SELECT product_name, price
FROM Products
WHERE price = (SELECT MAX(price) FROM Products);
#How many products are there in each category?
SELECT category, COUNT(*) AS category_count FROM Products GROUP BY category;
#Which customer has spent the most amount of money?
SELECT customer_id, SUM(total_amount) AS total_spent
FROM Orders
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 1;
#What are the top 5 best-selling products?
SELECT p.product_id, p.product_name, SUM(oi.quantity) AS total_quantity_sold
FROM Products p
JOIN OrderItems oi ON p.product_id = oi.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_quantity_sold DESC
LIMIT 5;
#How many orders were placed in a specific time period?
SELECT COUNT(*) AS order_count
FROM Orders
WHERE order_date >= '2023-01-01' AND order_date <= '2023-07-07';